<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/RI.Master" AutoEventWireup="true"
    CodeBehind="ChuteSetup.aspx.cs" Inherits="IHF.ApplicationLayer.Web.Admin.Setup.ChuteSetup" %>

<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>
<%--<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>--%>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <telerik:RadScriptManager ID="RadScriptManager2" runat="server">
    </telerik:RadScriptManager>
    <div>
        <table width="100%">
            <tr>
                <td style="text-align: center; color: Black; padding: 5px 5px 5px 5px;" >
                    Chute Setup
                </td>
            </tr>
        </table>
        <table width="100%">
            <tr>
                <asp:Label ID="Error" runat="server" Text="Label"></asp:Label>
            </tr>
        </table>
        <table>
            <tr>
                <td>
                    
                    <%--<telerik:RadScriptManager ID="RadScriptManager1" runat="server">
                    </telerik:RadScriptManager>--%>
                    <telerik:RadGrid ID="RadGrid1" runat="server" Width="100%" GridLines="None" AutoGenerateColumns="False"
                        PageSize="20" AllowSorting="True" AllowPaging="True" OnUpdateCommand="RadGrid1_UpdateCommand"
                        OnInsertCommand="RadGrid1_InsertCommand" OnNeedDataSource="RadGrid1_NeedDataSource"
                        ShowStatusBar="True" AllowFilteringByColumn="true" OnItemDataBound="RadGrid1_ItemDataBound"
                        OnItemCommand="RadGrid1_ItemCommand" AutoGenerateDeleteColumn="False" AutoGenerateEditColumn="False"
                        Font-Italic="False" Font-Overline="False" Font-Strikeout="False" Font-Underline="False">
                        <%--<ClientSettings>
                            <Scrolling AllowScroll="False" UseStaticHeaders="True" />
                        </ClientSettings>--%>
                        <AlternatingItemStyle Font-Bold="False" Font-Italic="False" Font-Overline="False"
                            Font-Strikeout="False" Font-Underline="False" HorizontalAlign="Left" VerticalAlign="Bottom"
                            Wrap="True" />
                        <MasterTableView DataKeyNames="chute_id" AllowMultiColumnSorting="True" Width="100%"
                            CommandItemDisplay="Top">
                            <CommandItemSettings ExportToPdfText="Export to Pdf"></CommandItemSettings>
                            <RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
                            </RowIndicatorColumn>
                            <ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
                            </ExpandCollapseColumn>
                            <Columns>
                                <telerik:GridBoundColumn UniqueName="chute_id" SortExpression="chute_id" HeaderText="Chute ID"
                                    DataField="chute_id" ReadOnly="true" AllowFiltering="False" AllowSorting="true">
                                    <HeaderStyle Width="60px" HorizontalAlign="Center"></HeaderStyle>
                                    <ItemStyle Width="60px" BorderStyle="Solid" />
                                </telerik:GridBoundColumn>
                                <telerik:GridTemplateColumn DataField="chlabel" HeaderText="Label" FilterControlWidth="35px"
                                    AllowFiltering="false">
                                    <EditItemTemplate>
                                        <telerik:RadTextBox ID="ch_label_TextBox" runat="server"  MaxLength = "8"/>
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="ch_label_TextBox"
                                            ErrorMessage="* Enter Chute Label">
                                        </asp:RequiredFieldValidator>
                                        
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="ChLabel" runat="server" Text='<%# Eval("chlabel") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle Width="85px"></HeaderStyle>
                                    <ItemStyle Width="85px"></ItemStyle>
                                </telerik:GridTemplateColumn>
                                <telerik:GridBoundColumn UniqueName="barcode" SortExpression="barcode" HeaderText="Barcode"
                                    DataField="barcode" ReadOnly="true" AllowFiltering="False" AllowSorting="true">
                                    <HeaderStyle Width="120px"></HeaderStyle>
                                    <ItemStyle Width="120px" BorderStyle="Solid" />
                                </telerik:GridBoundColumn>
                                <telerik:GridTemplateColumn DataField="statuscd_desc" HeaderText="Status" SortExpression="statuscd_desc"
                                    UniqueName="statuscd_desc" AllowFiltering="false" ReadOnly=true>
                                    <EditItemTemplate>
                                        <telerik:RadComboBox ID="ch_status_RadComboBox" runat="server" />
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="ch_status_RadComboBox"
                                            ErrorMessage="* Select Status">
                                        </asp:RequiredFieldValidator>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="chstatus" runat="server" Text='<%# Eval("statuscd_desc") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle Width="105px"></HeaderStyle>
                                    <ItemStyle Width="105px"></ItemStyle>
                                </telerik:GridTemplateColumn>
                                <telerik:GridBoundColumn UniqueName="status_cd" SortExpression="status_cd" HeaderText="Status"
                                    DataField="status_cd" Visible="false" ReadOnly="true" />
                                <telerik:GridBoundColumn UniqueName="chutetyp_id" SortExpression="chutetyp_id" HeaderText="Chute Type"
                                    DataField="chutetyp_id" ReadOnly="true" Visible="false" />
                                <telerik:GridTemplateColumn DataField="enb_ind_desc" HeaderText="Enable Indicator"
                                    SortExpression="enb_ind_desc" UniqueName="enb_ind_desc" AllowFiltering="false">
                                    <EditItemTemplate>
                                        <telerik:RadComboBox ID="ch_enb_ind_RadComboBox" runat="server" />
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator4" runat="server" ControlToValidate="ch_enb_ind_RadComboBox"
                                            ErrorMessage="* Select Enable Indicator">
                                        </asp:RequiredFieldValidator>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="chenind" runat="server" Text='<%# Eval("enb_ind_desc") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle Width="105px"></HeaderStyle>
                                    <ItemStyle Width="105px"></ItemStyle>
                                </telerik:GridTemplateColumn>
                               <%-- <telerik:GridTemplateColumn DataField="int_ind_desc" HeaderText="International Indicator"
                                    SortExpression="int_ind_desc" UniqueName="int_ind_desc" AllowFiltering="false">
                                    <EditItemTemplate>
                                        <telerik:RadComboBox ID="ch_int_ind_RadComboBox" runat="server" />
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator5" runat="server" ControlToValidate="ch_int_ind_RadComboBox"
                                            ErrorMessage="* Select International Indicator">
                                        </asp:RequiredFieldValidator>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="chintind" runat="server" Text='<%# Eval("int_ind_desc") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle Width="105px"></HeaderStyle>
                                    <ItemStyle Width="105px"></ItemStyle>
                                </telerik:GridTemplateColumn>--%>
                                <telerik:GridBoundColumn UniqueName="sort_ind" SortExpression="sort_ind" HeaderText="Sortable"
                                    DataField="sort_ind" ReadOnly="true" AllowFiltering="false" />
                                <telerik:GridBoundColumn UniqueName="trtype_id" SortExpression="trtype_id" HeaderText="Trolley Typid"
                                    DataField="trtype_id" ReadOnly="true" Visible="false" AllowFiltering="false" />
                                <telerik:GridTemplateColumn DataField="area_id" HeaderText="Area ID" SortExpression="area_id"
                                    UniqueName="area_id" AllowFiltering="true">
                                    <EditItemTemplate>
                                        <telerik:RadComboBox ID="ch_area_RadComboBox" runat="server" />
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator7" runat="server" ControlToValidate="ch_area_RadComboBox"
                                            ErrorMessage="* Select Manual Sort Area">
                                        </asp:RequiredFieldValidator>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="charea" runat="server" Text='<%# Eval("area_id") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle Width="40px"></HeaderStyle>
                                    <ItemStyle Width="40px"></ItemStyle>
                                </telerik:GridTemplateColumn>
                                
                                <telerik:GridBoundColumn UniqueName="area_desc" SortExpression="area_desc" HeaderText="Area"
                                    DataField="area_desc" ReadOnly="true" Visible="true" AllowFiltering="true" HeaderStyle-Width="60" ItemStyle-Width="60" />
                                
                                   

                                <telerik:GridTemplateColumn DataField="chutetyp_id" HeaderText="chute typ id" SortExpression="chute_typ_id"
                                    AllowFiltering="false" Visible=false >
                                    <ItemTemplate>
                                        <asp:Label ID="chtypid" runat="server" Text='<%# Eval("chutetyp_id") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                </telerik:GridTemplateColumn>

                                <%--<telerik:GridTemplateColumn DataField="Area_code" HeaderText="Code" FilterControlWidth="35px"  
                                AllowFiltering="false">
                                   
                                    <ItemTemplate>
                                        <asp:Label ID="lblArea_code" runat="server" Text='<%# Eval("Area_code") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle Width="65px" HorizontalAlign="Center"></HeaderStyle>
                                    <ItemStyle Width="65px"></ItemStyle>
                                </telerik:GridTemplateColumn>--%>
                                
                                <telerik:GridTemplateColumn DataField="chute_type" HeaderText="Chute Type" SortExpression="chute_type"
                                    UniqueName="chute_type" AllowFiltering="false">
                                    <EditItemTemplate>
                                        <telerik:RadComboBox ID="ch_type_RadComboBox" runat="server" AutoPostBack="true"
                                            OnSelectedIndexChanged="ch_type_RadComboBox_SelectedIndexChanged">
                                        </telerik:RadComboBox>
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="ch_type_RadComboBox"
                                            ErrorMessage="* Select Type">
                                        </asp:RequiredFieldValidator>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="chtype" runat="server" Text='<%# Eval("chute_type") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle Width="80px"></HeaderStyle>
                                    <ItemStyle Width="80px"></ItemStyle>
                                </telerik:GridTemplateColumn>
                                <telerik:GridTemplateColumn DataField="trolley_type" HeaderText="Trolley Type" SortExpression="trolley_type"
                                    UniqueName="trolley_type" AllowFiltering="false">
                                    <EditItemTemplate>
                                        <telerik:RadComboBox ID="trolleytype_RadComboBox" runat="server" />
                                        <asp:RequiredFieldValidator ID="RequiredFieldValidator6" runat="server" ControlToValidate="trolleytype_RadComboBox"
                                            ErrorMessage="* Select Trolley Type">
                                        </asp:RequiredFieldValidator>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="trtype" runat="server" Text='<%# Eval("trolley_type") %>'>
                                        </asp:Label>
                                    </ItemTemplate>
                                    <HeaderStyle Width="60px"></HeaderStyle>
                                    <ItemStyle Width="60px"></ItemStyle>
                                </telerik:GridTemplateColumn>
                                <telerik:GridEditCommandColumn ButtonType="ImageButton" UniqueName="EditCommandColumn"
                                    HeaderText="Edit">
                                    <HeaderStyle Width="50px" HorizontalAlign="Center" />
                                    <ItemStyle Width="50px" HorizontalAlign="Center" />
                                </telerik:GridEditCommandColumn>
                                <%--<telerik:GridButtonColumn UniqueName="Print" CommandName="Print" ButtonType="PushButton"
                                Text="Print" />--%>
                                <telerik:GridButtonColumn HeaderImageUrl="~/Images/print.gif" UniqueName="Print"
                                    CommandName="Print" ButtonType="ImageButton" Text="Print" ImageUrl="~/Images/print.gif"
                                    HeaderText="Print">
                                    <HeaderStyle Width="50px" HorizontalAlign="Center" />
                                    <ItemStyle Width="50px" HorizontalAlign="Center" />
                                </telerik:GridButtonColumn>
                            </Columns>
                            <EditFormSettings CaptionFormatString="Edit details for Chute ID {0}" CaptionDataField="chute_id">
                                <FormTableItemStyle Width="100%" Height="29px"></FormTableItemStyle>
                                <FormTableStyle GridLines="None" CellSpacing="0" CellPadding="2"></FormTableStyle>
                                <FormStyle Width="100%" BackColor="#eef2ea"></FormStyle>
                                <EditColumn ButtonType="ImageButton" />
                            </EditFormSettings>
                        </MasterTableView>
                        <FilterMenu EnableImageSprites="False">
                        </FilterMenu>
                        <HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default">
                        </HeaderContextMenu>
                    </telerik:RadGrid>
                </td>
            </tr>
        </table>
    </div>
</asp:Content>
