<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/RI.Master" AutoEventWireup="true"
    CodeBehind="OverflowToteSetup.aspx.cs" Inherits="IHF.ApplicationLayer.Web.Admin.Setup.OverflowToteSetup" %>

<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <table width="100%">
        <tr>
            <td style="text-align: center; color: Black; padding: 5px 5px 5px 5px;">
                Overflow Tote Printing
            </td>
        </tr>
    </table>
    <table width="100%">
        <tr>
            <td>
            <telerik:RadScriptManager ID="RadScriptManager1" runat="server">
                                </telerik:RadScriptManager>
                <telerik:RadGrid ID="RadGrid1" runat="server" Width="96%" GridLines="None" AutoGenerateColumns="False"
                    PageSize="13" AllowSorting="True" AllowPaging="True" OnUpdateCommand="RadGrid1_UpdateCommand"
                    OnNeedDataSource="RadGrid1_NeedDataSource" ShowStatusBar="True" AllowFilteringByColumn="true"
                    OnEditCommand="RadGrid1_EditCommand" OnItemDataBound="RadGrid1_ItemDataBound" OnItemCommand = "RadGrid1_ItemCommand"
                    AutoGenerateDeleteColumn="False" AutoGenerateEditColumn="False">
                    <MasterTableView DataKeyNames="tote_id" AllowMultiColumnSorting="True" Width="100%"
                        CommandItemDisplay="Top">
                        <CommandItemSettings ExportToPdfText="Export to Pdf"></CommandItemSettings>
                        <RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
                        </RowIndicatorColumn>
                        <ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
                        </ExpandCollapseColumn>
                        <Columns>
                            <telerik:GridBoundColumn UniqueName="tote_id" SortExpression="tote_id" HeaderText="Overflow Tote ID"
                                DataField="tote_id" ReadOnly="true" />
                            <telerik:GridBoundColumn UniqueName="tote_label" SortExpression="tote_label" HeaderText="Label"
                                DataField="tote_label" ReadOnly="true" />
                            <telerik:GridBoundColumn UniqueName="barcode" SortExpression="barcode" HeaderText="Barcode"
                                DataField="barcode" ReadOnly="true" />
                            <telerik:GridBoundColumn UniqueName="trolley_id" SortExpression="trolley_id" HeaderText="Trolley ID"
                                DataField="trolley_id" ReadOnly="true" Visible="false"/>
                            <telerik:GridBoundColumn UniqueName="loc_id" SortExpression="loc_id" HeaderText="Location ID"
                                DataField="loc_id" ReadOnly="true" Visible="false" />
                            <telerik:GridBoundColumn UniqueName="order_id" SortExpression="order_id" HeaderText="Order Number"
                                DataField="order_id" ReadOnly="true" Visible="true" />
                            <telerik:GridBoundColumn UniqueName="delete_ind" SortExpression="delete_ind" HeaderText="Delete Indicator"
                                DataField="delete_ind" ReadOnly="false" Visible="false"/>
                            <telerik:GridBoundColumn UniqueName="trolley_label" SortExpression="trolley_label" HeaderText="Trolley Label"
                                DataField="trolley_label" ReadOnly="false" />
                            <telerik:GridButtonColumn UniqueName="Print" CommandName="Print" ButtonType="PushButton"
                                Text="Print" />
                            <%--<telerik:GridButtonColumn UniqueName="PrintAll" CommandName="PrintAll" ButtonType="PushButton"
                                Text="PrintAll" />--%>
                        </Columns>
                        <EditFormSettings CaptionFormatString="Edit details for trolley with ID {0}" CaptionDataField="tote_id">
                            <FormTableItemStyle Width="100%" Height="29px"></FormTableItemStyle>
                            <FormTableStyle GridLines="None" CellSpacing="0" CellPadding="2"></FormTableStyle>
                            <FormStyle Width="100%" BackColor="#eef2ea"></FormStyle>
                            <EditColumn ButtonType="ImageButton" />
                        </EditFormSettings>
                    </MasterTableView>
                    <FilterMenu EnableImageSprites="False">
                    </FilterMenu>
                    <HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default">
                    </HeaderContextMenu>
                </telerik:RadGrid>
                <br />
                <br />
                <asp:Button ID="Btn_print_all" runat="server" onclick="Btn_print_all_Click" 
                    Text="Print All" />
            </td>
        </tr>
    </table>
</asp:Content>
