<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/Dashboard/IHFDashboard.Master"
    AutoEventWireup="true" CodeBehind="PackPriority.aspx.cs" Inherits="IHF.ApplicationLayer.Web.Pages.Dashboard.PackPriority" %>

<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:ScriptManager ID="ScriptManager1" runat="server" />
    <table width="100%">
        <tr>
            <td style="text-align: center; color: Black; padding: 5px 5px 5px 5px; font-size: small;">
                <b>Pack Priority Setup </b>
            </td>
        </tr>
    </table>
    <table width="100%">
        <tr>
            <td>
                <telerik:RadGrid ID="RadGrid2" runat="server" 
                    Width="100%" 
                    GridLines="Both" 
                    AutoGenerateColumns="False"
                    PageSize="30" 
                    AllowSorting="False" 
                    AllowPaging="True" 
                    OnNeedDataSource="RadGrid2_NeedDataSource"
                    ShowStatusBar="True" 
                    AllowFilteringByColumn="false" 
                    OnItemCommand="RadGrid2_ItemCommand"
                    OnItemDataBound="RadGrid2_ItemDataBound" 
                    AutoGenerateDeleteColumn="False" 
                    AutoGenerateEditColumn="true"
                    HorizontalAlign="Center"
                    OnUpdateCommand="RadGrid2_UpdateCommand"
                    OnEditCommand="RadGrid2_EditCommand" Skin="Outlook">
                    
                    <ExportSettings HideStructureColumns="true" />
                    
                    <MasterTableView DataKeyNames="criterion_name" 
                        AllowMultiColumnSorting="True" 
                        Width="100%"
                        CommandItemDisplay="Top">
                        <CommandItemSettings ShowAddNewRecordButton="false" />
                        <RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
                        </RowIndicatorColumn>
                        <ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
                        </ExpandCollapseColumn>
                        <Columns>
                            <telerik:GridTemplateColumn UniqueName="select" HeaderText="" >
                                <ItemTemplate>
                                    <%--<asp:Label ID="drilldown" runat="server" Text='<%# Eval("criterion_type") %>' />--%>
                                    <asp:HyperLink ID="HyperLink1" runat="server" Text='<%# Eval("criterion_type") %>' NavigateUrl="#"></asp:HyperLink>
                                </ItemTemplate>
                                <ItemStyle Width="60px" />
                            </telerik:GridTemplateColumn>
                            <telerik:GridBoundColumn UniqueName="criterion_name" SortExpression="criterion_name"
                                HeaderText="Criterion" DataField="criterion_name" ReadOnly="true">
                                <HeaderStyle Width="160px"></HeaderStyle>
                                <ItemStyle Width="160px"></ItemStyle>
                            </telerik:GridBoundColumn>
                            <telerik:GridBoundColumn UniqueName="criterion_type" SortExpression="criterion_type"
                                HeaderText="criterion_type" DataField="criterion_type" ReadOnly="true" Visible="false">
                            </telerik:GridBoundColumn>

                            <telerik:GridTemplateColumn DataField="criterion_weighting" 
                                HeaderText="Weight"  UniqueName="criterion_weighting">
                                <EditItemTemplate>
                                    
                                    <asp:TextBox runat="server" Text='<%# Bind("criterion_weighting") %>' ID="TB1"></asp:TextBox>
                                    <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="TB1"
                                        ErrorMessage="*Enter Weight" ForeColor="Red">
                                    </asp:RequiredFieldValidator>
                                    <asp:RangeValidator ID="RV1" 
                                        ControlToValidate="TB1"
                                        MinimumValue="0" MaximumValue="100" Type="Integer" ErrorMessage="*Enter a whole number in the range 1 to 100"
                                        ForeColor="Red" runat="server">
                                    </asp:RangeValidator>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="LB1" runat="server" Text='<%# Eval("criterion_weighting") %>' ></asp:Label>
                                </ItemTemplate>
                                <HeaderStyle Width="120px"></HeaderStyle>
                                <ItemStyle Width="120px"></ItemStyle>
                            </telerik:GridTemplateColumn>

                            <%--<telerik:GridBoundColumn UniqueName="criterion_weighting" SortExpression="criterion_weighting"
                                HeaderText="Weight" DataField="criterion_weighting">
                                
                            </telerik:GridBoundColumn>--%>
                            
                        </Columns>
                    </MasterTableView>
                    <FilterMenu EnableImageSprites="False">
                    </FilterMenu>
                    <HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default">
                    </HeaderContextMenu>
                </telerik:RadGrid>
                <br />
            </td>
        </tr>
    </table>
</asp:Content>
