<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/Dashboard/IHFDashboard.Master" AutoEventWireup="true" CodeBehind="TrolleyDetail.aspx.cs" Inherits="IHF.ApplicationLayer.Web.Pages.Dashboard.TrolleyDetail" %>
<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>


<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <table width="100%">
        <tr>
            <td style="text-align: center; color: Black; padding: 5px 5px 5px 5px; Font-Size: small;" >
                <b>TROLLEY DETAIL </b>
            </td>
        </tr>
    </table>
    <table width="100%">
        <tr>
            <td>
                

                
                <asp:Button ID="Button1" runat="server" OnClientClick="JavaScript: window.history.go(-1); return false;" Text="Back" />
                



                <telerik:RadScriptManager ID="RadScriptManager1" runat="server">
                </telerik:RadScriptManager>

                <telerik:RadGrid 
                        ID="RadGrid1" 
                        runat="server" 
                        Width="100%" 
                        GridLines="None" 
                        AutoGenerateColumns="False"
                        PageSize="20" 
                        AllowSorting="True" 
                        AllowPaging="True" 
                        OnNeedDataSource="RadGrid1_NeedDataSource"
                        ShowStatusBar="true" 
                        AllowFilteringByColumn="false" 
                        OnItemCommand="RadGrid1_ItemCommand"
                        OnItemDataBound="RadGrid1_ItemDataBound" 
                        AutoGenerateDeleteColumn="False" 
                        AutoGenerateEditColumn="False">
                    <MasterTableView DataKeyNames="trolley_id" AllowMultiColumnSorting="False" Width="100%"
                        CommandItemDisplay="Top">
                        <CommandItemSettings ShowAddNewRecordButton="false" />
                        <%--<CommandItemSettings ExportToPdfText="Export to Pdf"></CommandItemSettings>--%>
                        <RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
                        </RowIndicatorColumn>
                        <ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
                        </ExpandCollapseColumn>
                        <Columns>
                            <telerik:GridBoundColumn UniqueName="trolley_id" 
                                                    SortExpression="trolley_id" 
                                                    HeaderText="Trolley Id"
                                                    DataField="trolley_id" 
                                                    ReadOnly="true" 
                                                    Visible="false" />

                            <telerik:GridBoundColumn UniqueName="trolley_label" 
                                                    SortExpression="trolley_label"
                                                    HeaderText="Trolley Name" 
                                                    DataField="trolley_label" 
                                                    ReadOnly="true" />

                            <telerik:GridBoundColumn UniqueName="trolley_status" 
                                                    SortExpression="trolley_status" 
                                                    HeaderText="Status"
                                                    DataField="trolley_status" 
                                                    ReadOnly="true" />
                            
                            
                            
                            <telerik:GridBoundColumn UniqueName="total_orders" SortExpression="total_orders"
                                HeaderText="Total Orders" DataField="total_orders" ReadOnly="true" />
                            <telerik:GridBoundColumn UniqueName="packable_orders" SortExpression="packable_orders" HeaderText="Packable Orders"
                                DataField="packable_orders" ReadOnly="true" />
                            
                            <telerik:GridBoundColumn UniqueName="International" SortExpression="International" HeaderText="International"
                                DataField="International" ReadOnly="true" />
                        </Columns>
                    </MasterTableView>
                    <FilterMenu EnableImageSprites="False">
                    </FilterMenu>
                    <HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default">
                    </HeaderContextMenu>
                </telerik:RadGrid>
            </td>
        </tr>
    </table>
    <table width="100%">
        <tr>
            <td>
            
                <telerik:RadGrid ID="RadGrid2" runat="server" Width="100%" GridLines="None" AutoGenerateColumns="False"
                    PageSize="20" AllowSorting="True" AllowPaging="True" 
                    OnNeedDataSource="RadGrid2_NeedDataSource" ShowStatusBar="True" 
                    AllowFilteringByColumn="true" 
                    OnItemCommand="RadGrid2_ItemCommand" OnItemDataBound="RadGrid2_ItemDataBound"
                    AutoGenerateDeleteColumn="False" AutoGenerateEditColumn="False">

                    <ExportSettings HideStructureColumns="true" />    

                    <MasterTableView DataKeyNames="trolley_id" AllowMultiColumnSorting="True" Width="100%"
                        CommandItemDisplay="Top">
                        <CommandItemSettings ShowAddNewRecordButton="false"/>
                        <%--<CommandItemSettings ExportToPdfText="Export to Pdf"></CommandItemSettings>--%>
                       <RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
                        </RowIndicatorColumn>
                        <ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
                        </ExpandCollapseColumn>
                        <Columns>
                            <telerik:GridBoundColumn UniqueName="trolley_id" 
                                                    SortExpression="trolley_id" 
                                                    HeaderText="Trolley Id"
                                                    DataField="trolley_id" 
                                                    ReadOnly="true" 
                                                    Visible="false" />

                            

                            <%--<telerik:GridBoundColumn UniqueName="item_status" 
                                                    SortExpression="item_status" 
                                                    HeaderText="Item Status"
                                                    DataField="item_status" 
                                                    ReadOnly="true" />--%>

                            <telerik:GridTemplateColumn UniqueName="item_status" HeaderText="Item Status" AllowFiltering=false>
                                <ItemTemplate>
                                    <asp:Image ID="completeimage" runat="server" />
                                    <asp:Label ID="itemslocated" runat="server" Style="font-weight: bold;" Text='<%# Eval("item_status") %>' />
                                </ItemTemplate>
                                <ItemStyle Width="120px" />
                            </telerik:GridTemplateColumn>

                            <telerik:GridBoundColumn UniqueName="item_status_cd" 
                                                    SortExpression="item_status_cd" 
                                                    HeaderText="Status#"
                                                    DataField="item_status_cd" 
                                                    ReadOnly="true" 
                                                    Visible="false" 
                                                    FilterControlWidth="20px">
                            <HeaderStyle Width="40px"></HeaderStyle>
                            <ItemStyle Width="40px"></ItemStyle>
                            </telerik:GridBoundColumn>


                            <telerik:GridBoundColumn UniqueName="ordernumber" 
                                                    SortExpression="ordernumber" 
                                                    HeaderText="Order#"
                                                    DataField="ordernumber" 
                                                    ReadOnly="true" />
                            
                            

                            <telerik:GridBoundColumn UniqueName="itemnumber" 
                                                    SortExpression="itemnumber" 
                                                    HeaderText="Item#"
                                                    DataField="itemnumber" 
                                                    ReadOnly="true" />
                            
                           
                            <telerik:GridBoundColumn UniqueName="sku" 
                                                    SortExpression="sku" 
                                                    HeaderText="SKU"
                                                    DataField="sku" 
                                                    ReadOnly="true" 
                                                    FilterControlWidth="40px">
                            <HeaderStyle Width="60px"></HeaderStyle>
                            <ItemStyle Width="60px"></ItemStyle>
                            </telerik:GridBoundColumn>
                            
                            

                            
                            <telerik:GridBoundColumn UniqueName="sku_description" 
                                                    SortExpression="sku_description" 
                                                    HeaderText="SKU Desc"
                                                    DataField="sku_description" 
                                                    ReadOnly="true" />
                            
                           
                            
                            <telerik:GridBoundColumn UniqueName="location" 
                                                    SortExpression="location" 
                                                    HeaderText="Location"
                                                    DataField="location" 
                                                    ReadOnly="true" 
                                                    FilterControlWidth="40px">
                            <HeaderStyle Width="60px"></HeaderStyle>
                            <ItemStyle Width="60px"></ItemStyle>
                            </telerik:GridBoundColumn>
                            
                            <telerik:GridBoundColumn UniqueName="load_num" 
                                                    SortExpression="load_num"
                                                    HeaderText="Load#" 
                                                    DataField="load_num" 
                                                    ReadOnly="true" 
                                                    FilterControlWidth="50px">
                            <HeaderStyle Width="70px"></HeaderStyle>
                            <ItemStyle Width="70px"></ItemStyle>
                            </telerik:GridBoundColumn>
                            
                        </Columns>
                        
                    </MasterTableView>
                    
                    <FilterMenu EnableImageSprites="False">
                    </FilterMenu>
                    <HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default">
                    </HeaderContextMenu>
                </telerik:RadGrid>

                <asp:Button ID="Button2" runat="server" onclick="Button1_Click1" 
                    Text="Export to Excel" />
                <br />
            </td>
        </tr>
    </table>
    
    
</asp:Content>