<%@ Page Title="" Language="C#" MasterPageFile="~/Pages/Dashboard/IHFDashboard.Master" AutoEventWireup="true" 
CodeBehind="TrolleyOverview.aspx.cs" Inherits="IHF.ApplicationLayer.Web.Pages.Dashboard.TrolleyOverview" %>
<%--<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
</asp:Content>--%>


<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <table width="100%">
        <tr>
            <td style="text-align: center; color: Black; padding: 5px 5px 5px 5px; Font-Size: small;" >
                <b>TROLLEY OVERVIEW </b>
            </td>
        </tr>
    </table>
    <table width="100%">
        <tr>
            <td style="text-align: left; color: Black; padding: 5px 5px 5px 5px;" 
                clientidmode="Predictable">
                
                <asp:Label ID="LB_trlabel" runat="server" Font-Bold="True" 
                    Text="Trolley Name" BackColor="#99CCFF"></asp:Label>
                &nbsp;&nbsp;&nbsp;&nbsp;
                <asp:TextBox ID="TB_label" runat="server" Width="108px" BackColor="Silver"></asp:TextBox>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Label ID="LBtrstatus" runat="server" Font-Bold="True" 
                    Text="Trolley Status" BackColor="#99CCFF"></asp:Label>
                <asp:DropDownList ID="DD_status" runat="server" Height="20px" 
                    style="margin-left: 25px" Width="170px">
                </asp:DropDownList>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <br />
                
                <asp:Label ID="Label3" runat="server" Font-Bold="True" Text="Trolley Class" 
                    BackColor="#99CCFF"></asp:Label>
&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;<asp:DropDownList ID="DD_class" runat="server" Height="20px" 
                    style="margin-left: 0px" Width="110px">
                </asp:DropDownList>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;
                <asp:Label ID="LBsergrp" runat="server" Font-Bold="True" Text="Service Group" 
                    BackColor="#99CCFF"></asp:Label>
&nbsp;<asp:DropDownList ID="DD_sergrp" runat="server" Height="19px" 
                    style="margin-left: 20px" Width="170px">
                </asp:DropDownList>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <asp:Button ID="btn_search" runat="server" onclick="Button1_Click" 
                    Text="Search" />
                
            </td>
        </tr>
    </table>
    
    <table width="100%">
        <tr>
            <td>
            <telerik:RadScriptManager ID="RadScriptManager1" runat="server">
                                </telerik:RadScriptManager>
                <telerik:RadGrid ID="RadGrid2" runat="server" Width="100%" GridLines="None" AutoGenerateColumns="False"
                    PageSize="20" AllowSorting="True" AllowPaging="True" 
                    OnNeedDataSource="RadGrid2_NeedDataSource" ShowStatusBar="True" 
                    AllowFilteringByColumn="true" 
                    OnItemCommand="RadGrid2_ItemCommand" OnItemDataBound="RadGrid2_ItemDataBound"
                    AutoGenerateDeleteColumn="False" AutoGenerateEditColumn="False">
                    
                    <ExportSettings HideStructureColumns="true" />                   


                    <MasterTableView DataKeyNames="trolley_id" AllowMultiColumnSorting="True" Width="100%"
                        CommandItemDisplay="Top">
                        <CommandItemSettings ShowAddNewRecordButton="false" />
                        <%--<CommandItemSettings ExportToPdfText="Export to Pdf"></CommandItemSettings>--%>
                        <RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
                        </RowIndicatorColumn>
                        <ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
                        </ExpandCollapseColumn>
                        <Columns>
                            <telerik:GridBoundColumn UniqueName="trolley_id" SortExpression="trolley_id" HeaderText="Trolley Id"
                                DataField="trolley_id" ReadOnly="true" Visible="false" />
                            <%--<telerik:GridBoundColumn UniqueName="trolley_label" SortExpression="trolley_label"
                                HeaderText="Trolley#" DataField="trolley_label" ReadOnly="true" />--%>
                            <telerik:GridHyperLinkColumn
                                    HeaderText="Trolley#" 
                                    UniqueName="trolley_label"
                                    DataTextField="trolley_label"
                                    DataNavigateUrlFields="trolley_id"
                                    AllowFiltering="false"
                                    SortExpression="trolley_label"
                                    DataNavigateUrlFormatString="~/Pages/Dashboard/TrolleyDetail.aspx?trolley_id={0}">
                            </telerik:GridHyperLinkColumn> 


                            <%--<telerik:GridBoundColumn UniqueName="trolley_seq" SortExpression="trolley_seq" HeaderText="Trolley Seq"
                                DataField="trolley_seq" ReadOnly="true" Visible="false" />--%>
                            <telerik:GridBoundColumn UniqueName="trolley_status" 
                                                    SortExpression="trolley_status" 
                                                    HeaderText="Status"
                                                    DataField="trolley_status" 
                                                    ReadOnly="true" 
                                                    FilterControlWidth="60px">
                                        <HeaderStyle Width="80px" HorizontalAlign="Left" />
                                        <ItemStyle Width="80px" />

                            </telerik:GridBoundColumn>
                            <telerik:GridBoundColumn UniqueName="trolley_class" 
                                                    SortExpression="trolley_class"
                                                    HeaderText="Class" 
                                                    DataField="trolley_class" 
                                                    ReadOnly="true" 
                                                    FilterControlWidth="30px">
                                        <HeaderStyle Width="50px" HorizontalAlign="Left" />
                                        <ItemStyle Width="50px" />

                            </telerik:GridBoundColumn>
                            <telerik:GridBoundColumn UniqueName="trolley_type" SortExpression="trolley_type" HeaderText="Type"
                                DataField="trolley_type" ReadOnly="true" Visible="false"/>
                            <telerik:GridBoundColumn UniqueName="chute" 
                                                    SortExpression="chute" 
                                                    HeaderText="Chute"
                                                    DataField="chute" 
                                                    ReadOnly="true" 
                                                    FilterControlWidth="30px">
                                        <HeaderStyle Width="50px" HorizontalAlign="Left" />
                                        <ItemStyle Width="50px" />

                            </telerik:GridBoundColumn>
                            <telerik:GridBoundColumn 
                                UniqueName="total_orders" 
                                SortExpression="total_orders"
                                HeaderText="Total Orders" 
                                DataField="total_orders" 
                                ReadOnly="true" FilterControlWidth="50px">
                                <HeaderStyle Width="70px"></HeaderStyle>
                                <ItemStyle Width="70px"></ItemStyle>
                            </telerik:GridBoundColumn>

                            <telerik:GridBoundColumn 
                                UniqueName="packable_orders" 
                                SortExpression="packable_orders" 
                                HeaderText="Packable Orders"
                                DataField="packable_orders" 
                                ReadOnly="true" FilterControlWidth="50px">
                                <HeaderStyle Width="70px"></HeaderStyle>
                                <ItemStyle Width="70px"></ItemStyle>
                            </telerik:GridBoundColumn>

                            <%--<telerik:GridBoundColumn 
                            
                                UniqueName="percent_located" 
                                SortExpression="percent_located" 
                                HeaderText="% located"
                                DataField="percent_located" 
                                ReadOnly="true" 
                                FilterControlWidth="50px">
                                <HeaderStyle Width="670px"></HeaderStyle>
                                <ItemStyle Width="70px"></ItemStyle>
                            </telerik:GridBoundColumn>--%>

                            <telerik:GridTemplateColumn UniqueName="percent_located" HeaderText="% located" AllowFiltering=false SortExpression="percent_located">
                                <ItemTemplate>
                                    <asp:Image ID="completeimage" runat="server" />
                                    <asp:Label ID="itemslocated" runat="server" Style="font-weight: bold;" Text='<%# Eval("percent_located") %>' />
                                </ItemTemplate>
                                <ItemStyle Width="80px" />
                            </telerik:GridTemplateColumn>


                            <telerik:GridBoundColumn UniqueName="International" SortExpression="International" HeaderText="International"
                                DataField="International" ReadOnly="true" Visible="false"/>
                            <telerik:GridBoundColumn UniqueName="service_id" SortExpression="service_id" HeaderText="Service Id"
                                DataField="service_id" ReadOnly="true" Visible="false"/>
                            <telerik:GridBoundColumn 
                                UniqueName="service_desc" 
                                SortExpression="service_desc" 
                                HeaderText="Service Desc"
                                DataField="service_desc" 
                                ReadOnly="true" 
                                FilterControlWidth="50px">
                                <HeaderStyle Width="70px"></HeaderStyle>
                                <ItemStyle Width="70px"></ItemStyle>
                            </telerik:GridBoundColumn>

                            <%--<telerik:GridBoundColumn UniqueName="wrkst" SortExpression="wrkst" HeaderText="Workstation"
                                DataField="wrkst" ReadOnly="true" />--%>
                            <%--<telerik:GridHyperLinkColumn
                                    HeaderText="Workstation" 
                                    UniqueName="wrkst"
                                    DataTextField="wrkst"
                                    DataNavigateUrlFields="wrkst"
                                    DataNavigateUrlFormatString="">
                            </telerik:GridHyperLinkColumn> --%>

                            <telerik:GridTemplateColumn DataField="wrkst" 
                                HeaderText="Workstation"  UniqueName="wrkst" AllowFiltering="false" >
                                <ItemTemplate>
                                    <telerik:RadComboBox ID="wrkst_RadComboBox" runat="server" AutoPostBack="True">
                                    </telerik:RadComboBox>
                                    
                                </ItemTemplate>
                                
                                <HeaderStyle Width="80px"></HeaderStyle>
                                <ItemStyle Width="40px"></ItemStyle>
                            </telerik:GridTemplateColumn>

                            <telerik:GridBoundColumn 
                                UniqueName="trolley_seq" 
                                SortExpression="trolley_seq" 
                                HeaderText="Trolley Class#"
                                DataField="trolley_seq" 
                                ReadOnly="true" 
                                FilterControlWidth="20px">
                                <HeaderStyle Width="40px"></HeaderStyle>
                                <ItemStyle Width="40px"></ItemStyle>
                            </telerik:GridBoundColumn>
                        </Columns>
                        
                    </MasterTableView>
                    
                    <FilterMenu EnableImageSprites="False">
                    </FilterMenu>
                    <HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default">
                    </HeaderContextMenu>
                </telerik:RadGrid>
                <%--<asp:Button ID="Button1" runat="server" onclick="Button1_Click1" 
                    Text="Button" />--%>
                <br />

            </td>
        </tr>
    </table>
    
    
</asp:Content>

