//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ManifestServiceSoapBinding", Namespace="urn:DeliveryManager/services")]
public partial class ManifestServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback createManifestForFutureDespatchOperationCompleted;
    
    private System.Threading.SendOrPostCallback createManifestOperationCompleted;
    
    private System.Threading.SendOrPostCallback findConsignmentsOnManifestOperationCompleted;
    
    private System.Threading.SendOrPostCallback findManifestsOperationCompleted;
    
    private System.Threading.SendOrPostCallback findReadyToManifestRecordsOperationCompleted;
    
    private System.Threading.SendOrPostCallback sendManifestOperationCompleted;
    
    private System.Threading.SendOrPostCallback createManifestAsPdfOperationCompleted;
    
    /// <remarks/>
    //public ManifestServiceService() {
    //    this.Url = "http://dm-qa.metapack.com/dm/services/ManifestService";
    //}

    public ManifestServiceService(string url)
    {
        this.Url = url;
    }
    
    /// <remarks/>
    public event createManifestForFutureDespatchCompletedEventHandler createManifestForFutureDespatchCompleted;
    
    /// <remarks/>
    public event createManifestCompletedEventHandler createManifestCompleted;
    
    /// <remarks/>
    public event findConsignmentsOnManifestCompletedEventHandler findConsignmentsOnManifestCompleted;
    
    /// <remarks/>
    public event findManifestsCompletedEventHandler findManifestsCompleted;
    
    /// <remarks/>
    public event findReadyToManifestRecordsCompletedEventHandler findReadyToManifestRecordsCompleted;
    
    /// <remarks/>
    public event sendManifestCompletedEventHandler sendManifestCompleted;
    
    /// <remarks/>
    public event createManifestAsPdfCompletedEventHandler createManifestAsPdfCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:DeliveryManager/services", ResponseNamespace="urn:DeliveryManager/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("createManifestForFutureDespatchReturn")]
    public string[] createManifestForFutureDespatch(string carrierCode, string warehouseCode, string transactionType, System.DateTime despatchDate, bool specificDateOnly) {
        object[] results = this.Invoke("createManifestForFutureDespatch", new object[] {
                    carrierCode,
                    warehouseCode,
                    transactionType,
                    despatchDate,
                    specificDateOnly});
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincreateManifestForFutureDespatch(string carrierCode, string warehouseCode, string transactionType, System.DateTime despatchDate, bool specificDateOnly, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("createManifestForFutureDespatch", new object[] {
                    carrierCode,
                    warehouseCode,
                    transactionType,
                    despatchDate,
                    specificDateOnly}, callback, asyncState);
    }
    
    /// <remarks/>
    public string[] EndcreateManifestForFutureDespatch(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public void createManifestForFutureDespatchAsync(string carrierCode, string warehouseCode, string transactionType, System.DateTime despatchDate, bool specificDateOnly) {
        this.createManifestForFutureDespatchAsync(carrierCode, warehouseCode, transactionType, despatchDate, specificDateOnly, null);
    }
    
    /// <remarks/>
    public void createManifestForFutureDespatchAsync(string carrierCode, string warehouseCode, string transactionType, System.DateTime despatchDate, bool specificDateOnly, object userState) {
        if ((this.createManifestForFutureDespatchOperationCompleted == null)) {
            this.createManifestForFutureDespatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateManifestForFutureDespatchOperationCompleted);
        }
        this.InvokeAsync("createManifestForFutureDespatch", new object[] {
                    carrierCode,
                    warehouseCode,
                    transactionType,
                    despatchDate,
                    specificDateOnly}, this.createManifestForFutureDespatchOperationCompleted, userState);
    }
    
    private void OncreateManifestForFutureDespatchOperationCompleted(object arg) {
        if ((this.createManifestForFutureDespatchCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.createManifestForFutureDespatchCompleted(this, new createManifestForFutureDespatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:DeliveryManager/services", ResponseNamespace="urn:DeliveryManager/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("createManifestReturn")]
    public string[] createManifest(string carrierCode, string warehouseCode, string transactionType) {
        object[] results = this.Invoke("createManifest", new object[] {
                    carrierCode,
                    warehouseCode,
                    transactionType});
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincreateManifest(string carrierCode, string warehouseCode, string transactionType, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("createManifest", new object[] {
                    carrierCode,
                    warehouseCode,
                    transactionType}, callback, asyncState);
    }
    
    /// <remarks/>
    public string[] EndcreateManifest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string[])(results[0]));
    }
    
    /// <remarks/>
    public void createManifestAsync(string carrierCode, string warehouseCode, string transactionType) {
        this.createManifestAsync(carrierCode, warehouseCode, transactionType, null);
    }
    
    /// <remarks/>
    public void createManifestAsync(string carrierCode, string warehouseCode, string transactionType, object userState) {
        if ((this.createManifestOperationCompleted == null)) {
            this.createManifestOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateManifestOperationCompleted);
        }
        this.InvokeAsync("createManifest", new object[] {
                    carrierCode,
                    warehouseCode,
                    transactionType}, this.createManifestOperationCompleted, userState);
    }
    
    private void OncreateManifestOperationCompleted(object arg) {
        if ((this.createManifestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.createManifestCompleted(this, new createManifestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:DeliveryManager/services", ResponseNamespace="urn:DeliveryManager/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("findConsignmentsOnManifestReturn")]
    public Consignment[] findConsignmentsOnManifest(string manifestCode) {
        object[] results = this.Invoke("findConsignmentsOnManifest", new object[] {
                    manifestCode});
        return ((Consignment[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindConsignmentsOnManifest(string manifestCode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findConsignmentsOnManifest", new object[] {
                    manifestCode}, callback, asyncState);
    }
    
    /// <remarks/>
    public Consignment[] EndfindConsignmentsOnManifest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Consignment[])(results[0]));
    }
    
    /// <remarks/>
    public void findConsignmentsOnManifestAsync(string manifestCode) {
        this.findConsignmentsOnManifestAsync(manifestCode, null);
    }
    
    /// <remarks/>
    public void findConsignmentsOnManifestAsync(string manifestCode, object userState) {
        if ((this.findConsignmentsOnManifestOperationCompleted == null)) {
            this.findConsignmentsOnManifestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindConsignmentsOnManifestOperationCompleted);
        }
        this.InvokeAsync("findConsignmentsOnManifest", new object[] {
                    manifestCode}, this.findConsignmentsOnManifestOperationCompleted, userState);
    }
    
    private void OnfindConsignmentsOnManifestOperationCompleted(object arg) {
        if ((this.findConsignmentsOnManifestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findConsignmentsOnManifestCompleted(this, new findConsignmentsOnManifestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:DeliveryManager/services", ResponseNamespace="urn:DeliveryManager/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("findManifestsReturn")]
    public Manifest[] findManifests(string carrierCode, string warehouseCode, string transactionType, System.DateTime dateFrom, System.DateTime dateTo) {
        object[] results = this.Invoke("findManifests", new object[] {
                    carrierCode,
                    warehouseCode,
                    transactionType,
                    dateFrom,
                    dateTo});
        return ((Manifest[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindManifests(string carrierCode, string warehouseCode, string transactionType, System.DateTime dateFrom, System.DateTime dateTo, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findManifests", new object[] {
                    carrierCode,
                    warehouseCode,
                    transactionType,
                    dateFrom,
                    dateTo}, callback, asyncState);
    }
    
    /// <remarks/>
    public Manifest[] EndfindManifests(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((Manifest[])(results[0]));
    }
    
    /// <remarks/>
    public void findManifestsAsync(string carrierCode, string warehouseCode, string transactionType, System.DateTime dateFrom, System.DateTime dateTo) {
        this.findManifestsAsync(carrierCode, warehouseCode, transactionType, dateFrom, dateTo, null);
    }
    
    /// <remarks/>
    public void findManifestsAsync(string carrierCode, string warehouseCode, string transactionType, System.DateTime dateFrom, System.DateTime dateTo, object userState) {
        if ((this.findManifestsOperationCompleted == null)) {
            this.findManifestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindManifestsOperationCompleted);
        }
        this.InvokeAsync("findManifests", new object[] {
                    carrierCode,
                    warehouseCode,
                    transactionType,
                    dateFrom,
                    dateTo}, this.findManifestsOperationCompleted, userState);
    }
    
    private void OnfindManifestsOperationCompleted(object arg) {
        if ((this.findManifestsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findManifestsCompleted(this, new findManifestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:DeliveryManager/services", ResponseNamespace="urn:DeliveryManager/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("findReadyToManifestRecordsReturn")]
    public ReadyToManifestInfo[] findReadyToManifestRecords(string warehouseCode, string transactionType) {
        object[] results = this.Invoke("findReadyToManifestRecords", new object[] {
                    warehouseCode,
                    transactionType});
        return ((ReadyToManifestInfo[])(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginfindReadyToManifestRecords(string warehouseCode, string transactionType, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("findReadyToManifestRecords", new object[] {
                    warehouseCode,
                    transactionType}, callback, asyncState);
    }
    
    /// <remarks/>
    public ReadyToManifestInfo[] EndfindReadyToManifestRecords(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ReadyToManifestInfo[])(results[0]));
    }
    
    /// <remarks/>
    public void findReadyToManifestRecordsAsync(string warehouseCode, string transactionType) {
        this.findReadyToManifestRecordsAsync(warehouseCode, transactionType, null);
    }
    
    /// <remarks/>
    public void findReadyToManifestRecordsAsync(string warehouseCode, string transactionType, object userState) {
        if ((this.findReadyToManifestRecordsOperationCompleted == null)) {
            this.findReadyToManifestRecordsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindReadyToManifestRecordsOperationCompleted);
        }
        this.InvokeAsync("findReadyToManifestRecords", new object[] {
                    warehouseCode,
                    transactionType}, this.findReadyToManifestRecordsOperationCompleted, userState);
    }
    
    private void OnfindReadyToManifestRecordsOperationCompleted(object arg) {
        if ((this.findReadyToManifestRecordsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.findReadyToManifestRecordsCompleted(this, new findReadyToManifestRecordsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:DeliveryManager/services", ResponseNamespace="urn:DeliveryManager/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("sendManifestReturn")]
    public bool sendManifest(string manifestCode) {
        object[] results = this.Invoke("sendManifest", new object[] {
                    manifestCode});
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginsendManifest(string manifestCode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("sendManifest", new object[] {
                    manifestCode}, callback, asyncState);
    }
    
    /// <remarks/>
    public bool EndsendManifest(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((bool)(results[0]));
    }
    
    /// <remarks/>
    public void sendManifestAsync(string manifestCode) {
        this.sendManifestAsync(manifestCode, null);
    }
    
    /// <remarks/>
    public void sendManifestAsync(string manifestCode, object userState) {
        if ((this.sendManifestOperationCompleted == null)) {
            this.sendManifestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsendManifestOperationCompleted);
        }
        this.InvokeAsync("sendManifest", new object[] {
                    manifestCode}, this.sendManifestOperationCompleted, userState);
    }
    
    private void OnsendManifestOperationCompleted(object arg) {
        if ((this.sendManifestCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.sendManifestCompleted(this, new sendManifestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="urn:DeliveryManager/services", ResponseNamespace="urn:DeliveryManager/services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("createManifestAsPdfReturn")]
    public string createManifestAsPdf(string manifestCode) {
        object[] results = this.Invoke("createManifestAsPdf", new object[] {
                    manifestCode});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BegincreateManifestAsPdf(string manifestCode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("createManifestAsPdf", new object[] {
                    manifestCode}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndcreateManifestAsPdf(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void createManifestAsPdfAsync(string manifestCode) {
        this.createManifestAsPdfAsync(manifestCode, null);
    }
    
    /// <remarks/>
    public void createManifestAsPdfAsync(string manifestCode, object userState) {
        if ((this.createManifestAsPdfOperationCompleted == null)) {
            this.createManifestAsPdfOperationCompleted = new System.Threading.SendOrPostCallback(this.OncreateManifestAsPdfOperationCompleted);
        }
        this.InvokeAsync("createManifestAsPdf", new object[] {
                    manifestCode}, this.createManifestAsPdfOperationCompleted, userState);
    }
    
    private void OncreateManifestAsPdfOperationCompleted(object arg) {
        if ((this.createManifestAsPdfCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.createManifestAsPdfCompleted(this, new createManifestAsPdfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
//[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
//[System.SerializableAttribute()]
//[System.Diagnostics.DebuggerStepThroughAttribute()]
//[System.ComponentModel.DesignerCategoryAttribute("code")]
//[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DeliveryManager/types")]
//public partial class Consignment {
    
//    private bool alreadyPalletisedGoodsFlagField;
    
//    private string cardNumberField;
    
//    private string carrierCodeField;
    
//    private string carrierConsignmentCodeField;
    
//    private string carrierNameField;
    
//    private string carrierServiceCodeField;
    
//    private string carrierServiceNameField;
    
//    private double carrierServiceVATRateField;
    
//    private string cartonNumberField;
    
//    private string cashOnDeliveryCurrencyCodeField;
    
//    private DateRange committedCollectionWindowField;
    
//    private DateRange committedDeliveryWindowField;
    
//    private string consDestinationReferenceField;
    
//    private string consOriginReferenceField;
    
//    private string consRecipientReferenceField;
    
//    private string consReferenceField;
    
//    private string consSenderReferenceField;
    
//    private string consignmentCodeField;
    
//    private bool consignmentLevelDetailsFlagField;
    
//    private double consignmentValueField;
    
//    private string consignmentValueCurrencyCodeField;
    
//    private double consignmentValueCurrencyRateField;
    
//    private double consignmentWeightField;
    
//    private string custom1Field;
    
//    private string custom10Field;
    
//    private string custom2Field;
    
//    private string custom3Field;
    
//    private string custom4Field;
    
//    private string custom5Field;
    
//    private string custom6Field;
    
//    private string custom7Field;
    
//    private string custom8Field;
    
//    private string custom9Field;
    
//    private System.Nullable<System.DateTime> cutOffDateField;
    
//    private System.Nullable<System.DateTime> despatchDateField;
    
//    private System.Nullable<System.DateTime> earliestDeliveryDateField;
    
//    private string endVatNumberField;
    
//    private bool fragileGoodsFlagField;
    
//    private System.Nullable<System.DateTime> guaranteedDeliveryDateField;
    
//    private bool hazardousGoodsFlagField;
    
//    private double insuranceValueField;
    
//    private string insuranceValueCurrencyCodeField;
    
//    private double insuranceValueCurrencyRateField;
    
//    private bool liquidGoodsFlagField;
    
//    private string manifestGroupCodeField;
    
//    private double maxDimensionField;
    
//    private string metaCampaignKeyField;
    
//    private string metaCustomerKeyField;
    
//    private bool moreThanOneMetreGoodsFlagField;
    
//    private bool moreThanTwentyFiveKgGoodsFlagField;
    
//    private System.Nullable<System.DateTime> orderDateField;
    
//    private string orderNumberField;
    
//    private double orderValueField;
    
//    private int parcelCountField;
    
//    private Parcel[] parcelsField;
    
//    private string pickTicketNumberField;
    
//    private string pickupPointField;
    
//    private string podRequiredField;
    
//    private Property[] propertiesField;
    
//    private Address recipientAddressField;
    
//    private string recipientCodeField;
    
//    private string recipientContactPhoneField;
    
//    private string recipientEmailField;
    
//    private string recipientMobilePhoneField;
    
//    private string recipientNameField;
    
//    private string recipientNotificationTypeField;
    
//    private string recipientPhoneField;
    
//    private string recipientTimeZoneField;
    
//    private string recipientVatNumberField;
    
//    private Address returnAddressField;
    
//    private Address senderAddressField;
    
//    private string senderCodeField;
    
//    private string senderContactPhoneField;
    
//    private string senderEmailField;
    
//    private string senderMobilePhoneField;
    
//    private string senderNameField;
    
//    private string senderNotificationTypeField;
    
//    private string senderPhoneField;
    
//    private string senderTimeZoneField;
    
//    private string senderVatNumberField;
    
//    private string shipmentTypeCodeField;
    
//    private string shippingAccountField;
    
//    private double shippingChargeField;
    
//    private string shippingChargeCurrencyCodeField;
    
//    private double shippingChargeCurrencyRateField;
    
//    private double shippingCostField;
    
//    private string shippingCostCurrencyCodeField;
    
//    private double shippingCostCurrencyRateField;
    
//    private string signatoryOnCustomsField;
    
//    private string specialInstructions1Field;
    
//    private string specialInstructions2Field;
    
//    private string startVatNumberField;
    
//    private string statusField;
    
//    private double taxAndDutyField;
    
//    private string taxAndDutyCurrencyCodeField;
    
//    private double taxAndDutyCurrencyRateField;
    
//    private string taxDutyDeclarationCurrencyCodeField;
    
//    private string termsOfTradeCodeField;
    
//    private string transactionTypeField;
    
//    private bool twoManLiftFlagField;
    
//    /// <remarks/>
//    public bool alreadyPalletisedGoodsFlag {
//        get {
//            return this.alreadyPalletisedGoodsFlagField;
//        }
//        set {
//            this.alreadyPalletisedGoodsFlagField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string cardNumber {
//        get {
//            return this.cardNumberField;
//        }
//        set {
//            this.cardNumberField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string carrierCode {
//        get {
//            return this.carrierCodeField;
//        }
//        set {
//            this.carrierCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string carrierConsignmentCode {
//        get {
//            return this.carrierConsignmentCodeField;
//        }
//        set {
//            this.carrierConsignmentCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string carrierName {
//        get {
//            return this.carrierNameField;
//        }
//        set {
//            this.carrierNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string carrierServiceCode {
//        get {
//            return this.carrierServiceCodeField;
//        }
//        set {
//            this.carrierServiceCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string carrierServiceName {
//        get {
//            return this.carrierServiceNameField;
//        }
//        set {
//            this.carrierServiceNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    public double carrierServiceVATRate {
//        get {
//            return this.carrierServiceVATRateField;
//        }
//        set {
//            this.carrierServiceVATRateField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string cartonNumber {
//        get {
//            return this.cartonNumberField;
//        }
//        set {
//            this.cartonNumberField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string cashOnDeliveryCurrencyCode {
//        get {
//            return this.cashOnDeliveryCurrencyCodeField;
//        }
//        set {
//            this.cashOnDeliveryCurrencyCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public DateRange committedCollectionWindow {
//        get {
//            return this.committedCollectionWindowField;
//        }
//        set {
//            this.committedCollectionWindowField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public DateRange committedDeliveryWindow {
//        get {
//            return this.committedDeliveryWindowField;
//        }
//        set {
//            this.committedDeliveryWindowField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string consDestinationReference {
//        get {
//            return this.consDestinationReferenceField;
//        }
//        set {
//            this.consDestinationReferenceField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string consOriginReference {
//        get {
//            return this.consOriginReferenceField;
//        }
//        set {
//            this.consOriginReferenceField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string consRecipientReference {
//        get {
//            return this.consRecipientReferenceField;
//        }
//        set {
//            this.consRecipientReferenceField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string consReference {
//        get {
//            return this.consReferenceField;
//        }
//        set {
//            this.consReferenceField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string consSenderReference {
//        get {
//            return this.consSenderReferenceField;
//        }
//        set {
//            this.consSenderReferenceField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string consignmentCode {
//        get {
//            return this.consignmentCodeField;
//        }
//        set {
//            this.consignmentCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    public bool consignmentLevelDetailsFlag {
//        get {
//            return this.consignmentLevelDetailsFlagField;
//        }
//        set {
//            this.consignmentLevelDetailsFlagField = value;
//        }
//    }
    
//    /// <remarks/>
//    public double consignmentValue {
//        get {
//            return this.consignmentValueField;
//        }
//        set {
//            this.consignmentValueField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string consignmentValueCurrencyCode {
//        get {
//            return this.consignmentValueCurrencyCodeField;
//        }
//        set {
//            this.consignmentValueCurrencyCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    public double consignmentValueCurrencyRate {
//        get {
//            return this.consignmentValueCurrencyRateField;
//        }
//        set {
//            this.consignmentValueCurrencyRateField = value;
//        }
//    }
    
//    /// <remarks/>
//    public double consignmentWeight {
//        get {
//            return this.consignmentWeightField;
//        }
//        set {
//            this.consignmentWeightField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string custom1 {
//        get {
//            return this.custom1Field;
//        }
//        set {
//            this.custom1Field = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string custom10 {
//        get {
//            return this.custom10Field;
//        }
//        set {
//            this.custom10Field = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string custom2 {
//        get {
//            return this.custom2Field;
//        }
//        set {
//            this.custom2Field = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string custom3 {
//        get {
//            return this.custom3Field;
//        }
//        set {
//            this.custom3Field = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string custom4 {
//        get {
//            return this.custom4Field;
//        }
//        set {
//            this.custom4Field = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string custom5 {
//        get {
//            return this.custom5Field;
//        }
//        set {
//            this.custom5Field = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string custom6 {
//        get {
//            return this.custom6Field;
//        }
//        set {
//            this.custom6Field = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string custom7 {
//        get {
//            return this.custom7Field;
//        }
//        set {
//            this.custom7Field = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string custom8 {
//        get {
//            return this.custom8Field;
//        }
//        set {
//            this.custom8Field = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string custom9 {
//        get {
//            return this.custom9Field;
//        }
//        set {
//            this.custom9Field = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public System.Nullable<System.DateTime> cutOffDate {
//        get {
//            return this.cutOffDateField;
//        }
//        set {
//            this.cutOffDateField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public System.Nullable<System.DateTime> despatchDate {
//        get {
//            return this.despatchDateField;
//        }
//        set {
//            this.despatchDateField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public System.Nullable<System.DateTime> earliestDeliveryDate {
//        get {
//            return this.earliestDeliveryDateField;
//        }
//        set {
//            this.earliestDeliveryDateField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string endVatNumber {
//        get {
//            return this.endVatNumberField;
//        }
//        set {
//            this.endVatNumberField = value;
//        }
//    }
    
//    /// <remarks/>
//    public bool fragileGoodsFlag {
//        get {
//            return this.fragileGoodsFlagField;
//        }
//        set {
//            this.fragileGoodsFlagField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public System.Nullable<System.DateTime> guaranteedDeliveryDate {
//        get {
//            return this.guaranteedDeliveryDateField;
//        }
//        set {
//            this.guaranteedDeliveryDateField = value;
//        }
//    }
    
//    /// <remarks/>
//    public bool hazardousGoodsFlag {
//        get {
//            return this.hazardousGoodsFlagField;
//        }
//        set {
//            this.hazardousGoodsFlagField = value;
//        }
//    }
    
//    /// <remarks/>
//    public double insuranceValue {
//        get {
//            return this.insuranceValueField;
//        }
//        set {
//            this.insuranceValueField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string insuranceValueCurrencyCode {
//        get {
//            return this.insuranceValueCurrencyCodeField;
//        }
//        set {
//            this.insuranceValueCurrencyCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    public double insuranceValueCurrencyRate {
//        get {
//            return this.insuranceValueCurrencyRateField;
//        }
//        set {
//            this.insuranceValueCurrencyRateField = value;
//        }
//    }
    
//    /// <remarks/>
//    public bool liquidGoodsFlag {
//        get {
//            return this.liquidGoodsFlagField;
//        }
//        set {
//            this.liquidGoodsFlagField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string manifestGroupCode {
//        get {
//            return this.manifestGroupCodeField;
//        }
//        set {
//            this.manifestGroupCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    public double maxDimension {
//        get {
//            return this.maxDimensionField;
//        }
//        set {
//            this.maxDimensionField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string metaCampaignKey {
//        get {
//            return this.metaCampaignKeyField;
//        }
//        set {
//            this.metaCampaignKeyField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string metaCustomerKey {
//        get {
//            return this.metaCustomerKeyField;
//        }
//        set {
//            this.metaCustomerKeyField = value;
//        }
//    }
    
//    /// <remarks/>
//    public bool moreThanOneMetreGoodsFlag {
//        get {
//            return this.moreThanOneMetreGoodsFlagField;
//        }
//        set {
//            this.moreThanOneMetreGoodsFlagField = value;
//        }
//    }
    
//    /// <remarks/>
//    public bool moreThanTwentyFiveKgGoodsFlag {
//        get {
//            return this.moreThanTwentyFiveKgGoodsFlagField;
//        }
//        set {
//            this.moreThanTwentyFiveKgGoodsFlagField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public System.Nullable<System.DateTime> orderDate {
//        get {
//            return this.orderDateField;
//        }
//        set {
//            this.orderDateField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string orderNumber {
//        get {
//            return this.orderNumberField;
//        }
//        set {
//            this.orderNumberField = value;
//        }
//    }
    
//    /// <remarks/>
//    public double orderValue {
//        get {
//            return this.orderValueField;
//        }
//        set {
//            this.orderValueField = value;
//        }
//    }
    
//    /// <remarks/>
//    public int parcelCount {
//        get {
//            return this.parcelCountField;
//        }
//        set {
//            this.parcelCountField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("parcels", IsNullable=true)]
//    public Parcel[] parcels {
//        get {
//            return this.parcelsField;
//        }
//        set {
//            this.parcelsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string pickTicketNumber {
//        get {
//            return this.pickTicketNumberField;
//        }
//        set {
//            this.pickTicketNumberField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string pickupPoint {
//        get {
//            return this.pickupPointField;
//        }
//        set {
//            this.pickupPointField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string podRequired {
//        get {
//            return this.podRequiredField;
//        }
//        set {
//            this.podRequiredField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute("properties", IsNullable=true)]
//    public Property[] properties {
//        get {
//            return this.propertiesField;
//        }
//        set {
//            this.propertiesField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public Address recipientAddress {
//        get {
//            return this.recipientAddressField;
//        }
//        set {
//            this.recipientAddressField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string recipientCode {
//        get {
//            return this.recipientCodeField;
//        }
//        set {
//            this.recipientCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string recipientContactPhone {
//        get {
//            return this.recipientContactPhoneField;
//        }
//        set {
//            this.recipientContactPhoneField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string recipientEmail {
//        get {
//            return this.recipientEmailField;
//        }
//        set {
//            this.recipientEmailField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string recipientMobilePhone {
//        get {
//            return this.recipientMobilePhoneField;
//        }
//        set {
//            this.recipientMobilePhoneField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string recipientName {
//        get {
//            return this.recipientNameField;
//        }
//        set {
//            this.recipientNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string recipientNotificationType {
//        get {
//            return this.recipientNotificationTypeField;
//        }
//        set {
//            this.recipientNotificationTypeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string recipientPhone {
//        get {
//            return this.recipientPhoneField;
//        }
//        set {
//            this.recipientPhoneField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string recipientTimeZone {
//        get {
//            return this.recipientTimeZoneField;
//        }
//        set {
//            this.recipientTimeZoneField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string recipientVatNumber {
//        get {
//            return this.recipientVatNumberField;
//        }
//        set {
//            this.recipientVatNumberField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public Address returnAddress {
//        get {
//            return this.returnAddressField;
//        }
//        set {
//            this.returnAddressField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public Address senderAddress {
//        get {
//            return this.senderAddressField;
//        }
//        set {
//            this.senderAddressField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string senderCode {
//        get {
//            return this.senderCodeField;
//        }
//        set {
//            this.senderCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string senderContactPhone {
//        get {
//            return this.senderContactPhoneField;
//        }
//        set {
//            this.senderContactPhoneField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string senderEmail {
//        get {
//            return this.senderEmailField;
//        }
//        set {
//            this.senderEmailField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string senderMobilePhone {
//        get {
//            return this.senderMobilePhoneField;
//        }
//        set {
//            this.senderMobilePhoneField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string senderName {
//        get {
//            return this.senderNameField;
//        }
//        set {
//            this.senderNameField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string senderNotificationType {
//        get {
//            return this.senderNotificationTypeField;
//        }
//        set {
//            this.senderNotificationTypeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string senderPhone {
//        get {
//            return this.senderPhoneField;
//        }
//        set {
//            this.senderPhoneField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string senderTimeZone {
//        get {
//            return this.senderTimeZoneField;
//        }
//        set {
//            this.senderTimeZoneField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string senderVatNumber {
//        get {
//            return this.senderVatNumberField;
//        }
//        set {
//            this.senderVatNumberField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string shipmentTypeCode {
//        get {
//            return this.shipmentTypeCodeField;
//        }
//        set {
//            this.shipmentTypeCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string shippingAccount {
//        get {
//            return this.shippingAccountField;
//        }
//        set {
//            this.shippingAccountField = value;
//        }
//    }
    
//    /// <remarks/>
//    public double shippingCharge {
//        get {
//            return this.shippingChargeField;
//        }
//        set {
//            this.shippingChargeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string shippingChargeCurrencyCode {
//        get {
//            return this.shippingChargeCurrencyCodeField;
//        }
//        set {
//            this.shippingChargeCurrencyCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    public double shippingChargeCurrencyRate {
//        get {
//            return this.shippingChargeCurrencyRateField;
//        }
//        set {
//            this.shippingChargeCurrencyRateField = value;
//        }
//    }
    
//    /// <remarks/>
//    public double shippingCost {
//        get {
//            return this.shippingCostField;
//        }
//        set {
//            this.shippingCostField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string shippingCostCurrencyCode {
//        get {
//            return this.shippingCostCurrencyCodeField;
//        }
//        set {
//            this.shippingCostCurrencyCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    public double shippingCostCurrencyRate {
//        get {
//            return this.shippingCostCurrencyRateField;
//        }
//        set {
//            this.shippingCostCurrencyRateField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string signatoryOnCustoms {
//        get {
//            return this.signatoryOnCustomsField;
//        }
//        set {
//            this.signatoryOnCustomsField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string specialInstructions1 {
//        get {
//            return this.specialInstructions1Field;
//        }
//        set {
//            this.specialInstructions1Field = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string specialInstructions2 {
//        get {
//            return this.specialInstructions2Field;
//        }
//        set {
//            this.specialInstructions2Field = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string startVatNumber {
//        get {
//            return this.startVatNumberField;
//        }
//        set {
//            this.startVatNumberField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string status {
//        get {
//            return this.statusField;
//        }
//        set {
//            this.statusField = value;
//        }
//    }
    
//    /// <remarks/>
//    public double taxAndDuty {
//        get {
//            return this.taxAndDutyField;
//        }
//        set {
//            this.taxAndDutyField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string taxAndDutyCurrencyCode {
//        get {
//            return this.taxAndDutyCurrencyCodeField;
//        }
//        set {
//            this.taxAndDutyCurrencyCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    public double taxAndDutyCurrencyRate {
//        get {
//            return this.taxAndDutyCurrencyRateField;
//        }
//        set {
//            this.taxAndDutyCurrencyRateField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string taxDutyDeclarationCurrencyCode {
//        get {
//            return this.taxDutyDeclarationCurrencyCodeField;
//        }
//        set {
//            this.taxDutyDeclarationCurrencyCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string termsOfTradeCode {
//        get {
//            return this.termsOfTradeCodeField;
//        }
//        set {
//            this.termsOfTradeCodeField = value;
//        }
//    }
    
//    /// <remarks/>
//    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
//    public string transactionType {
//        get {
//            return this.transactionTypeField;
//        }
//        set {
//            this.transactionTypeField = value;
//        }
//    }
    
//    /// <remarks/>
//    public bool twoManLiftFlag {
//        get {
//            return this.twoManLiftFlagField;
//        }
//        set {
//            this.twoManLiftFlagField = value;
//        }
//    }
//}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DeliveryManager/types")]
public partial class ReadyToManifestInfo {
    
    private string carrierCodeField;
    
    private int consignmentCountField;
    
    private int parcelCountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string carrierCode {
        get {
            return this.carrierCodeField;
        }
        set {
            this.carrierCodeField = value;
        }
    }
    
    /// <remarks/>
    public int consignmentCount {
        get {
            return this.consignmentCountField;
        }
        set {
            this.consignmentCountField = value;
        }
    }
    
    /// <remarks/>
    public int parcelCount {
        get {
            return this.parcelCountField;
        }
        set {
            this.parcelCountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:DeliveryManager/types")]
public partial class Manifest {
    
    private string carrierCodeField;
    
    private int consignmentCountField;
    
    private System.Nullable<System.DateTime> createdDateTimeField;
    
    private string manifestCodeField;
    
    private string manifestStatusField;
    
    private System.Nullable<System.DateTime> sentDateTimeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string carrierCode {
        get {
            return this.carrierCodeField;
        }
        set {
            this.carrierCodeField = value;
        }
    }
    
    /// <remarks/>
    public int consignmentCount {
        get {
            return this.consignmentCountField;
        }
        set {
            this.consignmentCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> createdDateTime {
        get {
            return this.createdDateTimeField;
        }
        set {
            this.createdDateTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string manifestCode {
        get {
            return this.manifestCodeField;
        }
        set {
            this.manifestCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string manifestStatus {
        get {
            return this.manifestStatusField;
        }
        set {
            this.manifestStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> sentDateTime {
        get {
            return this.sentDateTimeField;
        }
        set {
            this.sentDateTimeField = value;
        }
    }
}



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void createManifestForFutureDespatchCompletedEventHandler(object sender, createManifestForFutureDespatchCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class createManifestForFutureDespatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal createManifestForFutureDespatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void createManifestCompletedEventHandler(object sender, createManifestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class createManifestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal createManifestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void findConsignmentsOnManifestCompletedEventHandler(object sender, findConsignmentsOnManifestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findConsignmentsOnManifestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findConsignmentsOnManifestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Consignment[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Consignment[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void findManifestsCompletedEventHandler(object sender, findManifestsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findManifestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findManifestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public Manifest[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((Manifest[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void findReadyToManifestRecordsCompletedEventHandler(object sender, findReadyToManifestRecordsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class findReadyToManifestRecordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal findReadyToManifestRecordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ReadyToManifestInfo[] Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ReadyToManifestInfo[])(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void sendManifestCompletedEventHandler(object sender, sendManifestCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class sendManifestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal sendManifestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public bool Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
public delegate void createManifestAsPdfCompletedEventHandler(object sender, createManifestAsPdfCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.1")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class createManifestAsPdfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal createManifestAsPdfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
