//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.AppMessages", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan item for sorting load..
        /// </summary>
        internal static string MSIS1 {
            get {
                return ResourceManager.GetString("MSIS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Put the item to chute {0} , and scan the chute barcode..
        /// </summary>
        internal static string MSIS2 {
            get {
                return ResourceManager.GetString("MSIS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Scan.
        /// </summary>
        internal static string MSIS3 {
            get {
                return ResourceManager.GetString("MSIS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Sorted, select next load to sort..
        /// </summary>
        internal static string MSLS1 {
            get {
                return ResourceManager.GetString("MSLS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the area for sorting..
        /// </summary>
        internal static string MSMNU1 {
            get {
                return ResourceManager.GetString("MSMNU1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the load for sorting..
        /// </summary>
        internal static string MSMNU2 {
            get {
                return ResourceManager.GetString("MSMNU2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No load exists for selected area..
        /// </summary>
        internal static string MSMNU3 {
            get {
                return ResourceManager.GetString("MSMNU3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan next item..
        /// </summary>
        internal static string MSPC1 {
            get {
                return ResourceManager.GetString("MSPC1", resourceCulture);
            }
        }
    }
}
