<%@ Page Language="C#"  MasterPageFile="~/Pages/RI.Master" Culture="en-GB"  AutoEventWireup="true" CodeBehind="TestLoadCreation.aspx.cs" Inherits="IHF.ApplicationLayer.Web.Pages.TestHarness.TestLoacCreation" %>
<%@ Register Assembly="Telerik.Web.UI" Namespace="Telerik.Web.UI" TagPrefix="telerik" %>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <telerik:RadScriptManager ID="RadScriptManager1" runat="server" AsyncPostBackTimeout="2000">
    </telerik:RadScriptManager>
    <div>
        <asp:ObjectDataSource ID="ObjectDataSource1" runat="server" 
            SelectMethod="GetLines" 
            TypeName="IHF.BusinessLayer.DataAccessObjects.TestLoadDAO" 
            DataObjectTypeName="IHF.BusinessLayer.DataAccessObjects.TestLoadDAO" 
            DeleteMethod="DeleteLine" InsertMethod="InsertLine" UpdateMethod="UpdateLine">
        </asp:ObjectDataSource>
        <telerik:RadCodeBlock ID="RadCodeBlock1" runat="server">
        <script type="text/javascript">
            var currentLoadingPanel = null;
            var currentUpdatedControl = null;
            var btn1 = $find("<%= Button1.ClientID%>");

            function requestStart(sender, args) {
                currentLoadingPanel = $find("<%= RadAjaxLoadingPanel1.ClientID%>");
                btn1 = $find("<%= Button1.ClientID%>");

                if (args.get_eventTarget() == "<%= Button1.UniqueID %>") {
                    currentUpdatedControl = "<%= Panel1.ClientID %>";
                    //show the loading panel over the updated control   
                    currentLoadingPanel.show(currentUpdatedControl);
                }
            }
            function responseEnd() {
                //hide the loading panel and clean up the global variables
                //btn1 = $find("<%= Button1.ClientID%>");               
                if (currentLoadingPanel != null) {
                    currentLoadingPanel.hide(currentUpdatedControl);
                }
                currentUpdatedControl = null;
                currentLoadingPanel = null;
                //if (!btn1.get_enabled()) {
                //    btn1.set_enabled(true);
                //}
            }
        </script>
    </telerik:RadCodeBlock>
        <telerik:RadAjaxManager ID="RadAjaxManager1" runat="server" 
            DefaultLoadingPanelID="RadAjaxLoadingPanel1">
            <AjaxSettings>
                <telerik:AjaxSetting AjaxControlID="Button1">
                    <UpdatedControls>
                        <telerik:AjaxUpdatedControl ControlID="lbmsg" />
                        <telerik:AjaxUpdatedControl ControlID="RadGrid1" 
                            LoadingPanelID="RadAjaxLoadingPanel1" />
                    </UpdatedControls>
                </telerik:AjaxSetting>
            </AjaxSettings>
            <ClientEvents OnRequestStart="requestStart" OnResponseEnd="responseEnd"></ClientEvents>
        </telerik:RadAjaxManager>
            <asp:Panel ID="Panel1" runat="server">
        <asp:Label ID="lbmsg" runat="server" ForeColor="Red" Visible="False" 
            Width="500px"></asp:Label>
        <telerik:RadAjaxLoadingPanel ID="RadAjaxLoadingPanel1" runat="server" Skin="Default">
        </telerik:RadAjaxLoadingPanel>

        <telerik:RadGrid ID="RadGrid1" runat="server" AutoGenerateColumns="False" 
            CellSpacing="0" AutoGenerateDeleteColumn="True" Culture="en-GB"
            AutoGenerateEditColumn="True" Height="600px" ShowFooter="True" 
            Skin="Simple" AllowAutomaticDeletes="True" AllowAutomaticInserts="True" 
            AllowAutomaticUpdates="True" DataSourceID="ObjectDataSource1" 
            GridLines="None" oninsertcommand="RadGrid1_InsertCommand" 
            onitemcommand="RadGrid1_ItemCommand" onitemcreated="RadGrid1_ItemCreated">
<MasterTableView CommandItemDisplay="Top" 
                DataKeyNames="LineId" DataSourceID="ObjectDataSource1">
<CommandItemSettings ExportToPdfText="Export to PDF"></CommandItemSettings>

<RowIndicatorColumn FilterControlAltText="Filter RowIndicator column">
<HeaderStyle Width="20px"></HeaderStyle>
</RowIndicatorColumn>

<ExpandCollapseColumn FilterControlAltText="Filter ExpandColumn column">
</ExpandCollapseColumn>

    <Columns>
        <telerik:GridBoundColumn DataField="LineId" 
            FilterControlAltText="Filter LineId column" HeaderText="LineId" 
            UniqueName="LineId" DataType="System.Decimal" SortExpression="LineId" 
            Display="False" ReadOnly="True" Visible="False">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="OrderCount" DataType="System.Decimal" 
            FilterControlAltText="Filter OrderCount column" HeaderText="Order Count" 
            SortExpression="OrderCount" UniqueName="OrderCount">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="ItemsPerOrder" DataType="System.Decimal" 
            FilterControlAltText="Filter ItemsPerOrder column" HeaderText="Items Per Order" 
            SortExpression="ItemsPerOrder" UniqueName="ItemsPerOrder">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="CarrierServiceGroup" 
            FilterControlAltText="Filter CarrierServiceGroup column" 
            HeaderText="Carrier Service Group" SortExpression="CarrierServiceGroup" 
            UniqueName="CarrierServiceGroup">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="ItemVolume" DataType="System.Decimal" 
            FilterControlAltText="Filter ItemVolume column" HeaderText="Item Volume (mm3)" 
            SortExpression="ItemVolume" UniqueName="ItemVolume">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="CountryCode" 
            FilterControlAltText="Filter CountryCode column" HeaderText="Country Code" 
            SortExpression="CountryCode" UniqueName="CountryCode">
        </telerik:GridBoundColumn>
        <telerik:GridBoundColumn DataField="DeliverByDate"  DataFormatString="{0:dd/MM/yyyy}"
            FilterControlAltText="Filter deliverbydatecolumn column" 
            HeaderText="Delivery By Date" UniqueName="deliverbydatecolumn">
        </telerik:GridBoundColumn>
    </Columns>

<EditFormSettings>
<EditColumn FilterControlAltText="Filter EditCommandColumn column"></EditColumn>
</EditFormSettings>
</MasterTableView>

            <HeaderStyle Height="10px" />

<FilterMenu EnableImageSprites="False"></FilterMenu>

<HeaderContextMenu CssClass="GridContextMenu GridContextMenu_Default"></HeaderContextMenu>
        </telerik:RadGrid>
            <asp:Button ID="Button1" runat="server" onclick="Button1_Click" 
        Text="Create Load" />
        </asp:Panel>
              
    </div>


      

</asp:Content>
